### ISSUE TITLE
设置的className没有加上去

### ISSUE THREAD

**Issue by yangtoude** [yujinjin/mobile-message#1]
```
import MobileMessage from 'mobile-message'
import 'mobile-message/dist/message.css'

Vue.use(MobileMessage, {
  className: 'mobile-message'
})

      this.$message.confirm('是否确认？', (result, $body) => {
        if (result) {
           console.log('已确认')
        }
      })
```

![image](https://user-images.githubusercontent.com/17309758/69685112-324b0d00-10f6-11ea-8c7c-e2aa0e261410.png)

**Comment by yujinjin** [comment]
@yangtoude  你用的confirm是默认指定的'confirm'的样式，主要是用来自定义模式（this.$message({})）的。对于this.$message.confirm这种方式用自定义的样式需要这样用:`this.$message.confirm({contents:'是否确认？', className: "confirm"}, (result, $body) => {
        if (result) {
           console.log('已确认')
        }
      })`

**Comment by yangtoude** [comment]
哦哦，好的。
